version: "3.9"

services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3308:3306"
    networks:
      - rest-azure-docker-network
  backend:
    image: rest-azure-docker-webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "44300:80"
    depends_on:
      - db
    networks:
      - rest-azure-docker-network
networks:
  rest-azure-docker-network:
    driver: bridge